### ISSUE TITLE
MonkeyPack - Modal

### ISSUE THREAD

**Issue by caio-emidio** [Em1dio/monkey-invest-web#10]

**Comment by plovinicius** [comment]
Para qual tela seria esse overlay?
Seria um overlay global (tela inteira) ?

**Comment by caio-emidio** [comment]
@plovinicius vai tentar fazer essa task?

**Comment by plovinicius** [comment]
@caio-emidio sim, vou ver se consigo pegar essa e mais alguma no fds se ngm tiver feito ainda

**Comment by caio-emidio** [comment]
Em conversa com o Kelviny:
https://www.w3schools.com/howto/howto_css_overlay.asp
![image](https://user-images.githubusercontent.com/5342402/110713089-36bb0c80-81f9-11eb-97b1-2e3fc5a13096.png)

**Comment by ItaloCanturil** [comment]
Qual a ideia do modal?

To querendo praticar Vue, manda a ideia que faço

**Comment by caio-emidio** [comment]
Feito.
