### ISSUE TITLE
Refresh automático

### ISSUE THREAD

**Issue by alissonsleal** [Em1dio/monkey-invest-web#27]
Seria interessante atualizar automaticamente a tabela de ações.
Atualmente temos que apertar no botão de adicionar a stock e depois apertar no botão de refresh.
![image](https://user-images.githubusercontent.com/19809377/110223920-123bf900-7eb6-11eb-9d38-6754bd62966d.png)

**Comment by caio-emidio** [comment]
Pra isso preciso dar uma estudada em VUEX. Caso voce saiba. Manda ver mano!

**Comment by caio-emidio** [comment]
Botao foi removido.

**Comment by caio-emidio** [comment]
Realizado com PR' #32
