### ISSUE TITLE
Dashboard 2.0

### ISSUE THREAD

**Issue by alissonsleal** [Em1dio/monkey-invest-web#34]
## UI Concept do Novo Dashboard

![image](https://user-images.githubusercontent.com/19809377/111019152-1bd4cd80-839c-11eb-93f9-3cf1b38b6e51.png)

[Link do Figma](https://www.figma.com/file/QOtIxpJdSeIoSYys4SPACr/Monkey-Invest?node-id=0:1)

**Comment by caio-emidio** [comment]
Esse Dashboard ja esta feito com modelo feito pelo @daviprm_
